### PR TITLE
[4.x] High severity security issue in `minimist`-dependency

### PR DESCRIPTION
**Pull request by rlsf**
updated dependencies according to npm audit fix.

### CODE REVIEW

**Comment by jaylinski** [comment]
@rlsf In https://github.com/handlebars-lang/handlebars.js/discussions/1842 you wrote:

> please merge it and release a new version, as currently handlebars suffers from a critical CVE

When doing a fresh install of `handlebars`, the `npm audit`-command currently reports the following:

```
minimist  *
Severity: high
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix --force`
Will install handlebars@4.7.5, which is a breaking change
node_modules/minimist
  handlebars  >=4.7.6
  Depends on vulnerable versions of minimist
  node_modules/handlebars

2 high severity vulnerabilities
```

This PR will not solve those issues, since the lock-file is ignored when installing a package as dependency.

Also the `minimist`-vulnerability will only be solved when https://github.com/substack/minimist/pull/165 is merged and tagged, nothing we can do here.

In our current `master` (designated version 5) we got already rid of the `minimist` dependency, so I will invest some time for a new major release.

**Comment by jaylinski** [comment]
Maybe we should use https://github.com/meszaros-lajos-gyorgy/minimist-lite instead of `minimist`. :thinking:

**Comment by rlsf** [comment]
indeed, i didn't notice that the update didn't upgrade minimist.
minimist v1.2.6, with a fix to the aforementioned CVE was released 3 hours ago.
i've updated the PR with it.

**Comment by jesperhagstrom** [comment]
Sorry, noticed this PR after I created https://github.com/handlebars-lang/handlebars.js/pull/1843, however this PR seems to update in the 5.x-branch while mine updates in the 4.x. I'll close my PR if not applicable.

**Comment by jaylinski** [comment]
As mentioned before, the lock file is only used when directly checking out this repo and running `npm install`.

When installing handlebars in your project via `npm i handlebars` and running `npm audit`, there are no security issues:

Bildschirmfoto 2022-03-22 um 09 37 16

**Comment by Jones-S** [comment]
Sorry this may be a dumb question: but am trying to resolve this issue and I had handlebars installed before. I tried removing the handlebars package and readding it. 
```
$ yarn remove handlebars 
$ yarn cache clean
$ yarn add handlebars```

but still it would always install the version `v1.2.5` of minimist.

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/7059580/166827115-7b72a138-0179-4106-af85-87c5ec18ec45.png">

Can you tell me how I can the installation actually follow the indication in handlebars `minimist@^1.2.5` to install v1.2.6?

Thank you and cheers

**Pull request closed without merging**
